name: wmbusmeters
adopt-info: wmbusmeters
summary: "Program receives and decodes WMBus telegrams"
description: |
  The program receives and decodes C1, T1 or S1 telegrams
  (using the wireless mbus protocol) to acquire utility meter readings.
  The readings can then be published using MQTT, curled to a REST api,
  inserted into a database or stored in a log file.
  Following must be executed "sudo snap connect wmbusmeters:raw-usb core:raw-usb"
  to allow snap read USB devices and check that root user of your system is
  added to group that can read USB devices

base: core18
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64

  - build-on: armhf
    run-on: armhf

parts:
  script:
    plugin: dump
    source: snap/local/
    prime:
      - launcher.sh

  wmbusmeters:
    source: "https://github.com/weetmuts/wmbusmeters.git"
    source-type: git
    override-pull: |
      snapcraftctl pull
      if [ -n "$(git describe --tags | grep -)" ]; then
        GIT_REV="$(git describe --tags | cut -f1,2 -d'-')"
        snapcraftctl set-version "$GIT_REV"
        snapcraftctl set-grade devel
      else
        GIT_VER="$(git describe --tags)"
        snapcraftctl set-version "$GIT_VER"
        snapcraftctl set-grade stable
      fi
    plugin: autotools
    build-packages:
      - g++
      - make
      - librtlsdr-dev
      - libncurses5-dev
    stage-packages:
      - mosquitto-clients
      - curl
      - dash
      - sysvinit-utils
      - libusb-1.0-0
      - rtl-sdr
    prime:
      - sbin/
      - usr/bin/
      - usr/lib/
      - bin/
      - lib/
      - etc/wmbusmeters.conf

  rtl-wmbus:
    source: "https://github.com/weetmuts/rtl-wmbus.git"
    plugin: make
    artifacts:
      - build/rtl_wmbus
    organize:
      build/rtl_wmbus: usr/bin/rtl_wmbus
    prime:
      - usr/bin/rtl_wmbus

  rtl-433:
    source: "https://github.com/merbanan/rtl_433.git"
    plugin: cmake
    organize:
      bin/rtl_433: usr/bin/rtl_433
    prime:
      - usr/bin/rtl_433

apps:
  wmbusmeters:
    command: bin/sh $SNAP/launcher.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - raw-usb
      - system-observe

layout:
  /usr/bin/wmbusmeters:
    bind-file: $SNAP/usr/bin/wmbusmeters
  /sbin/killall5:
    bind-file: $SNAP/sbin/killall5
#rtl
  /usr/bin/rtl_433:
    bind-file: $SNAP/usr/bin/rtl_433
  /usr/bin/rtl_sdr:
    bind-file: $SNAP/usr/bin/rtl_sdr
  /usr/bin/rtl_wmbus:
    bind-file: $SNAP/usr/bin/rtl_wmbus
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/librtlsdr.so.0:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/librtlsdr.so.0
  /lib/$SNAPCRAFT_ARCH_TRIPLET/libusb-1.0.so.0:
    symlink: $SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET/libusb-1.0.so.0
#mosquitto
  /usr/bin/mosquitto_pub:
    bind-file: $SNAP/usr/bin/mosquitto_pub
  /usr/bin/mosquitto_sub:
    bind-file: $SNAP/usr/bin/mosquitto_sub
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmosquitto.so.1:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmosquitto.so.1
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcares.so.2:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcares.so.2
#curl
  /usr/bin/curl:
    bind-file: $SNAP/usr/bin/curl
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcurl.so.4:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcurl.so.4
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libnghttp2.so.14:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libnghttp2.so.14
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/librtmp.so.1:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/librtmp.so.1
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpsl.so.5:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpsl.so.5
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libldap_r-2.4.so.2:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libldap_r-2.4.so.2
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/liblber-2.4.so.2:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/liblber-2.4.so.2
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsasl2.so.2:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsasl2.so.2
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgssapi.so.3:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgssapi.so.3
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimntlm.so.0:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimntlm.so.0
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasn1.so.8:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasn1.so.8
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhcrypto.so.4:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhcrypto.so.4
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libroken.so.18:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libroken.so.18
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libwind.so.0:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libwind.so.0
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimbase.so.1:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimbase.so.1
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhx509.so.5:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhx509.so.5
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libkrb5.so.26:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libkrb5.so.26